'use strict';
// Templates for the files that setup writes into a project. Each is a function of
// the detect() result. Placeholders look like `<!-- hx:fill: hint -->`; setup
// reports them so the model fills them from the real code.
const FILL_RE = /<!--\s*hx:fill:\s*(.*?)\s*-->/g;

function fill(hint) {
  return `<!-- hx:fill: ${hint} -->`;
}

function checksBlock(stack) {
  if (!stack.checks.length) {
    return `- Test all: ${fill('exact command to run all tests')}\n` +
      `- Lint / format: ${fill('exact lint and format commands, or "none"')}\n` +
      `- Build: ${fill('exact build command, or "none"')}`;
  }
  return stack.checks.map((c) => `- \`${c}\``).join('\n');
}

/** "(package manager: pnpm)" / "(build tool: ./mvnw)" — empty when unknown. */
function toolSuffix(stack) {
  if (!stack.packageManager) return '';
  const label = stack.kind === 'maven' || stack.kind === 'gradle' ? 'build tool' : 'package manager';
  return ` (${label}: ${stack.packageManager})`;
}

/** First check command that runs tests, or null. */
function testCommand(stack) {
  return (stack.checks || []).find((c) => /\btest\b|pytest/.test(c)) || null;
}

function rootAgents(stack, name) {
  const pm = toolSuffix(stack);
  return `# ${name} — agent rules

Keep this file under 4000 characters. Only facts the model cannot guess.

## Build and test${pm}
Run in this order before saying anything is done:
${checksBlock(stack)}
${stack.workspaces ? '- Monorepo: run the commands from the repo root; they cover all workspaces.\n' : ''}
## Project layout
${fill('3-6 lines: main folders and what lives in each (src/, tests/, config)')}

## Conventions
${fill('3-8 rules specific to this codebase: naming, error handling, how tests are organised, what to import from where')}

## Do not
${fill('files or actions the agent must not touch, e.g. generated code, prod config, lockfiles')}

## Harness
- Project checks: skill \`project-checks\`. Harness state: \`.agents/state/\` (not committed).
- Check this setup with \`/hx-core:doctor\`.
`;
}

function rulesTests(stack) {
  const cmd = testCommand(stack);
  const runner = cmd ? `\`${cmd}\`` : 'the project test command';
  const globs = stack.testGlobs && stack.testGlobs.length ? stack.testGlobs : ['**/*.test.*', '**/*.spec.*', '**/__tests__/**'];
  return `---
trigger: glob
globs: ${JSON.stringify(globs)}
description: Conventions for test files in this project
---
# Test conventions
- Run tests with ${runner}; run a single file first, then the whole suite.
${fill('test framework and style: vitest/jest/node:test, describe/test naming, fixtures location, what must not be mocked')}
`;
}

function rulesTypescript() {
  return `---
trigger: glob
globs: ["**/*.ts", "**/*.tsx"]
description: TypeScript conventions for this project
---
# TypeScript conventions
- Type-check before claiming a change compiles.
${fill('strictness, allowed use of any, module style (ESM/CJS), where shared types live, import ordering')}
`;
}

function projectChecksSkill(stack, name) {
  const steps = stack.checks.length
    ? stack.checks.map((c, i) => `${i + 1}. \`${c}\``).join('\n')
    : `1. ${fill('command 1 (type check or compile)')}\n2. ${fill('command 2 (lint)')}\n3. ${fill('command 3 (tests)')}`;
  return `---
name: project-checks
description: >-
  Run the checks for ${name} (type check, lint, tests, build) in the right order
  and read the results. Use before saying a change is done, before committing,
  and when /hx-workflows:verify asks for the project's checks.
metadata:
  icon: "🧪"
---

# Project checks

Run each command with \`run_command\` and wait for it to finish. Stop at the first
failure and report it; do not continue to the next command.

${steps}

## Reading results
- Exit code 0 and no "FAIL"/"error" lines → pass.
- Quote the first failing test or error with file and line.
${fill('anything special: slow tests to skip locally, env vars needed, flaky tests known')}

## Done when
Every command above exits 0 in this session.
`;
}

function hooksJson() {
  return JSON.stringify({
    'project-post-edit-lint': {
      PostToolUse: [
        {
          matcher: 'write_to_file|replace_file_content|multi_replace_file_content',
          hooks: [{ type: 'command', command: 'node ./hooks/post-edit-lint.js', timeout: 10 }],
        },
      ],
    },
  }, null, 2) + '\n';
}

function postEditLintHook(stack) {
  const lint = stack.lint || null;
  const lintCmd = lint ? lint.cmd : '';
  const exts = lint ? lint.exts : [];
  const nonEmpty = Boolean(lint && lint.nonEmptyIsIssue);
  return `#!/usr/bin/env node
'use strict';
// PostToolUse hook (generated by hx-core setup): lint the file that was just
// edited. It never modifies source files and never blocks; stdout is always {}.
// agy shows hook stderr to nobody, so results go to .agents/state/lint.json and
// the hx-guard PreInvocation hook injects them into the next model turn.
// Runs with cwd = the .agents/ directory.
const fs = require('fs');
const path = require('path');
const { spawnSync } = require('child_process');

const LINT = ${JSON.stringify(lintCmd)}; // empty string disables linting
const EXT = ${JSON.stringify(exts)};
const NON_EMPTY_IS_ISSUE = ${nonEmpty}; // e.g. gofmt -l prints the file name and exits 0
const MAX_NOTICES = 20;
const MAX_TEXT = 600;

function addNotice(root, file, text) {
  const dir = path.join(root, '.agents', 'state');
  const p = path.join(dir, 'lint.json');
  let state = { notices: [], reminded: {} };
  try {
    const parsed = JSON.parse(fs.readFileSync(p, 'utf8'));
    if (parsed && typeof parsed === 'object') state = { notices: Array.isArray(parsed.notices) ? parsed.notices : [], reminded: parsed.reminded && typeof parsed.reminded === 'object' ? parsed.reminded : {} };
  } catch (_) { /* missing or corrupt: start fresh */ }
  state.notices.push({ at: new Date().toISOString(), source: 'project-lint', file, text: String(text).slice(0, MAX_TEXT) });
  while (state.notices.length > MAX_NOTICES) state.notices.shift();
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(p, JSON.stringify(state, null, 2) + '\\n');
}

function main() {
  let input = {};
  try { input = JSON.parse(fs.readFileSync(0, 'utf8') || '{}'); } catch (_) { /* ignore */ }
  const root = (input.workspacePaths && input.workspacePaths[0]) || path.resolve(process.cwd(), '..');
  const args = (input.toolCall && input.toolCall.args) || {};
  const file = args.TargetFile;
  if (!LINT || !file || !EXT.includes(path.extname(file))) return;
  const abs = path.isAbsolute(file) ? file : path.join(root, file);
  if (!fs.existsSync(abs)) return;
  const [cmd, ...rest] = LINT.split(' ');
  const r = spawnSync(cmd, [...rest, abs], { cwd: root, encoding: 'utf8', shell: process.platform === 'win32', timeout: 8000 });
  const out = (r.stdout || '') + (r.stderr || '');
  const issue = r.status !== 0 || (NON_EMPTY_IS_ISSUE && (r.stdout || '').trim() !== '');
  if (issue) addNotice(root, path.relative(root, abs), out.trim() || (r.error ? r.error.message : 'lint failed (exit ' + r.status + ')'));
}

try { main(); } catch (err) { process.stderr.write('[project-lint] ' + err.message + '\\n'); }
process.stdout.write('{}\\n');
`;
}

/** Ordered list of files setup generates: [relative path, template fn, condition fn]. */
const TEMPLATES = [
  ['AGENTS.md', rootAgents],
  ['.agents/rules/tests.md', rulesTests],
  ['.agents/rules/typescript.md', rulesTypescript, (s) => s.typescript === true],
  ['.agents/skills/project-checks/SKILL.md', projectChecksSkill],
  ['.agents/hooks.json', hooksJson],
  ['.agents/hooks/post-edit-lint.js', postEditLintHook],
];

/** Every hx:fill hint in a text, in order. */
function fillsIn(text) {
  return [...text.matchAll(FILL_RE)].map((m) => m[1]);
}

module.exports = { TEMPLATES, fillsIn, FILL_RE, fill, postEditLintHook, testCommand };
